name: Publish database release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Setup rye
        uses: eifinger/setup-rye@v4

      - name: Run version update script
        run: rye sync && rye run scrape

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Discard changes in databases/
        run: git restore --staged databases && git checkout -- databases

      - name: Commit updated files
        run: |
          git add --force pages
          git commit -m "update: caching additional pages" || echo "No changes to commit"

      - name: Push Changes to GitHub
        run: git push

      - name: Create Release timestamp
        id: timestamp
        run: echo "timestamp=$(python gen_timestamp.py)" >> $GITHUB_OUTPUT
        # run: echo "version=$(python -c "import json; print(json.load(open('databases/weapons.json'))['metadata']['1']['version'])")" >> $GITHUB_OUTPUT
        #

      # - name: Create tag name label
      #   id: tag_name
      #   run: echo "tag_name=$(python -c "from datetime import datetime; print(datetime.now().strftime('%a-%B-%Y_%H-%M-%S'))")" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.timestamp.outputs.timestamp }}
          release_name: Limipieda Release ${{ steps.timestamp.outputs.timestamp }}
          draft: false
          prerelease: false

      - name: Assets release
        uses: softprops/action-gh-release@v2
        with:
          if: startsWith(github.ref, 'refs/tags/')
          tag_name: Limipedia_v${{ steps.timestamp.outputs.timestamp }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            databases/weapons.json
            databases/defgears.json
            databases/monsters.json
            databases/abilities.json
            databases/furniture.json
